- name: Descompilar APK
        run: |
          java -jar APKEditor.jar d -i app-debug.apk -o apk_decompiled
          # Muestra el contenido generado para verificar la estructura
          ls -la apk_decompiled

      - name: Reemplazar iconos
        run: |
          # Busca y reemplaza ic_launcher en cualquier subdirectorio dentro de apk_decompiled
          find apk_decompiled -name "ic_launcher*.png" -exec cp logo.png {} \;
