name: Cambiar Icono y Firmar APK

on:
  workflow_dispatch: # Permite ejecutar la acción manualmente con el botón Run workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Descargar uber-apk-signer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Usa la CLI de GitHub para descargar el archivo .jar de la última release oficial
          gh release download --repo PatrickF1/uber-apk-signer --pattern "*.jar" --clobber
          # Renombra el archivo descargado para asegurar un nombre limpio y estándar
          mv uber-apk-signer*.jar uber-apk-signer.jar

      - name: Descompilar APK
        run: |
          java -jar APKEditor.jar d -i app-debug.apk -o apk_decompiled
          ls -la apk_decompiled

      - name: Reemplazar iconos
        run: |
          # Busca y reemplaza ic_launcher en cualquier subcarpeta dentro de apk_decompiled
          find apk_decompiled -name "ic_launcher*.png" -exec cp logo.png {} \;

      - name: Recompilar APK
        run: |
          java -jar APKEditor.jar b -i apk_decompiled -o app-modificada.apk

      - name: Firmar APK
        run: |
          java -jar uber-apk-signer.jar --apks app-modificada.apk --out output/

      - name: Subir el APK final como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Con-Nuevo-Icono
          path: output/*.apk
